spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/wayfare}
    username: ${DB_USERNAME:wayfare}
    password: ${DB_PASSWORD:wayfare}

  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true

app:
  base-url: http://localhost:8080
